#!/bin/sh

CMD_NAME="arcleaner"

kernel_name=`uname -s`
IS_MAC_OS=false
if [ $kernel_name = "Darwin" ]; then
    IS_MAC_OS=true
fi

if ! $IS_MAC_OS; then # for Linux only
    alias greadlink="readlink"
fi

REAL_PATH=`greadlink -e "$0"`
if [ $? -ne 0 ]; then
    REAL_PATH="$0"
fi

CMD_DIR=`dirname "$REAL_PATH"`
JAR_PATH=$CMD_DIR/androidResourceCleaner.jar

if [ $# -eq 0 ]; then
    java -jar $JAR_PATH $CMD_NAME
else
    LINT_RESULT_XML_FILE=$1
    echo "Clean unused resources according to $LINT_RESULT_XML_FILE..."
    java -jar $JAR_PATH $CMD_NAME $@
fi
